import { Category, Product } from '../types';

export const STORE_CONFIG = {
  name: 'Crust & Crave',
  shortName: 'CC',
  tagline: 'Artisanal Pizzas • Handcrafted Crust',
  freeDeliveryText: 'Free Delivery',
  phone1: '7300760917',
  phone2: '9056351220',
  whatsappNumber: '917300760917',
  currencySymbol: '₹',
  address: 'Mc Kinney, Texas',
};

export const FALLBACK_CATEGORIES: Category[] = [
  {
    id: 'pizza',
    name: 'Pizza',
    desc: 'Artisanal stone-baked pizzas',
    order: 1,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'burgers',
    name: 'Burger',
    desc: 'Handcrafted gourmet smash burgers',
    order: 2,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'sides',
    name: 'Sides',
    desc: 'Crispy finger foods & sides',
    order: 3,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'beverages',
    name: 'Drinks',
    desc: 'Chilled shakes, sodas & mojitos',
    order: 4,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=500&q=80',
  },
  {
    id: 'dessert',
    name: 'Dessert',
    desc: 'Decadent sweet treats',
    order: 5,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=500&q=80',
  },
];

export const FALLBACK_PRODUCTS: Product[] = [
  // ── Popular Now ──
  {
    id: 'pop-1',
    cat: 'pizza',
    section: 'Popular Now',
    name: 'Truffle Mushroom Pizza',
    desc: 'San Marzano tomatoes, fior di latte mozzarella, sautéed wild mushrooms, white truffle oil & microgreens.',
    sizes: { Small: 199, Medium: 399, Large: 549 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    prepTime: '25 min',
    calories: '580 kcal',
    isAvailable: true,
    order: 1,
  },
  {
    id: 'pop-2',
    cat: 'burgers',
    section: 'Popular Now',
    name: 'Chic Burger',
    desc: 'Double seasoned smash patty, melted aged cheddar, crisp iceberg lettuce, tomato & house secret sauce on brioche.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80',
    rating: 4.7,
    prepTime: '18 min',
    calories: '459 kcal',
    isAvailable: true,
    order: 2,
  },
  {
    id: 'pop-3',
    cat: 'pizza',
    section: 'Popular Now',
    name: 'Artisanal Pepperoni Feast',
    desc: 'Smoky beef/turkey pepperoni, melted buffalo mozzarella, hot honey drizzle & fresh oregano.',
    sizes: { Small: 229, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    prepTime: '20 min',
    calories: '650 kcal',
    isAvailable: true,
    order: 3,
  },
  {
    id: 'pop-4',
    cat: 'sides',
    section: 'Popular Now',
    name: 'Crispy Truffle Fries',
    desc: 'Golden crisp skin-on fries tossed in white truffle oil, grated parmesan & fresh rosemary herbs.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=80',
    rating: 4.6,
    prepTime: '12 min',
    calories: '360 kcal',
    isAvailable: true,
    order: 4,
  },

  // ── Recommended ──
  {
    id: 'rec-1',
    cat: 'burgers',
    section: 'Recommended',
    name: 'Smoky BBQ Bacon Burger',
    desc: 'Char-grilled patty with smoked bacon rashers, caramelized sweet onions, smoked gouda & bourbon bbq sauce.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    prepTime: '20 min',
    calories: '540 kcal',
    isAvailable: true,
    order: 5,
  },
  {
    id: 'rec-2',
    cat: 'pizza',
    section: 'Recommended',
    name: 'Four Cheese Margherita',
    desc: 'Aged parmesan, creamy gorgonzola, fresh buffalo mozzarella and rich ricotta with extra virgin olive oil.',
    sizes: { Small: 219, Medium: 429, Large: 579 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    prepTime: '22 min',
    calories: '620 kcal',
    isAvailable: true,
    order: 6,
  },
  {
    id: 'rec-3',
    cat: 'beverages',
    section: 'Recommended',
    name: 'Belgian Chocolate Shake',
    desc: 'Decadent dark Belgian cocoa, vanilla bean cream, chocolate fudge syrup and crunchy chocolate pearls.',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    prepTime: '8 min',
    calories: '340 kcal',
    isAvailable: true,
    order: 7,
  },
  {
    id: 'rec-4',
    cat: 'dessert',
    section: 'Recommended',
    name: 'Molten Choco Lava Cake',
    desc: 'Oozing warm Belgian chocolate center baked to perfection, dusted with pure cane powdered sugar.',
    price: 109,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    prepTime: '10 min',
    calories: '380 kcal',
    isAvailable: true,
    order: 8,
  },

  // ── Artisanal Pizzas ──
  {
    id: 'piz-1',
    cat: 'pizza',
    section: 'Artisanal Pizzas',
    name: 'Garden Pesto & Burrata',
    desc: 'House-made basil pesto, heirloom cherry tomatoes, roasted garlic, topped with whole cold burrata.',
    sizes: { Small: 239, Medium: 459, Large: 619 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    prepTime: '22 min',
    calories: '590 kcal',
    isAvailable: true,
    order: 9,
  },
  {
    id: 'piz-2',
    cat: 'pizza',
    section: 'Artisanal Pizzas',
    name: 'Spicy Diavola Napoletana',
    desc: 'Calabrian hot soppressata, crushed red chilies, hot chili honey, fior di latte and fresh oregano.',
    sizes: { Small: 229, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    prepTime: '20 min',
    calories: '610 kcal',
    isAvailable: true,
    order: 10,
  },

  // ── Gourmet Burgers & Sides ──
  {
    id: 'bur-1',
    cat: 'burgers',
    section: 'Gourmet Burgers',
    name: 'Crispy Nashville Hot Burger',
    desc: 'Spicy cayenne buttermilk chicken patty, bread-and-butter pickles, creamy coleslaw on toasted brioche.',
    price: 159,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=700&q=80',
    rating: 4.7,
    prepTime: '15 min',
    calories: '510 kcal',
    isAvailable: true,
    order: 11,
  },
  {
    id: 'bev-1',
    cat: 'beverages',
    section: 'Shakes & Refreshers',
    name: 'Sparkling Mint Mojito',
    desc: 'Fresh lime wedges, hand-muddled garden mint, cane sugar syrup and chilled fizzy club soda.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80',
    rating: 4.7,
    prepTime: '5 min',
    calories: '140 kcal',
    isAvailable: true,
    order: 12,
  },
];

export const MAX_CART_QTY = 99;
